const skins = [
  {
    abbreviation: "",
    clothesId: 1,
    id: 1,
    isTopic: 0,
    name: "羊了个羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_00",
  },
  {
    abbreviation: "",
    clothesId: 2,
    id: 2,
    isTopic: 0,
    name: "卷羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_01",
  },
  {
    abbreviation: "",
    clothesId: 3,
    id: 3,
    isTopic: 0,
    name: "节日羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_02",
  },
  {
    abbreviation: "",
    clothesId: 4,
    id: 4,
    isTopic: 0,
    name: "披羊皮的狼",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_03",
  },
  {
    abbreviation: "",
    clothesId: 5,
    id: 5,
    isTopic: 0,
    name: "汉堡羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_04",
  },
  {
    abbreviation: "",
    clothesId: 6,
    id: 6,
    isTopic: 0,
    name: "水手羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_05",
  },
  {
    abbreviation: "",
    clothesId: 7,
    id: 7,
    isTopic: 0,
    name: "乌龟羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_06",
  },
  {
    abbreviation: "书生",
    clothesId: 8,
    id: 8,
    isTopic: 1,
    name: "书生羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The01A",
  },
  {
    abbreviation: "武生",
    clothesId: 9,
    id: 9,
    isTopic: 1,
    name: "武生羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The01B",
  },
  {
    abbreviation: "猫猫",
    clothesId: 10,
    id: 10,
    isTopic: 1,
    name: "猫猫羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The02A",
  },
  {
    abbreviation: "狗狗",
    clothesId: 11,
    id: 11,
    isTopic: 1,
    name: "狗狗羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The02B",
  },
  {
    abbreviation: "黑",
    clothesId: 12,
    id: 12,
    isTopic: 1,
    name: "黑羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The03A",
  },
  {
    abbreviation: "白",
    clothesId: 13,
    id: 13,
    isTopic: 1,
    name: "白羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The03B",
  },
  {
    abbreviation: "",
    clothesId: 14,
    id: 14,
    isTopic: 0,
    name: "西瓜羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_07",
  },
  {
    abbreviation: "",
    clothesId: 15,
    id: 15,
    isTopic: 0,
    name: "建设羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_08",
  },
  {
    abbreviation: "",
    clothesId: 16,
    id: 16,
    isTopic: 0,
    name: "炸虾羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_09",
  },
  {
    abbreviation: "",
    clothesId: 17,
    id: 17,
    isTopic: 0,
    name: "米饭羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_10",
  },
  {
    abbreviation: "",
    clothesId: 18,
    id: 18,
    isTopic: 0,
    name: "恐龙羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_11",
  },
  {
    abbreviation: "",
    clothesId: 19,
    id: 19,
    isTopic: 0,
    name: "煎蛋羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_12",
  },
  {
    abbreviation: "",
    clothesId: 20,
    id: 20,
    isTopic: 0,
    name: "公主羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_13",
  },
  {
    abbreviation: "",
    clothesId: 21,
    id: 21,
    isTopic: 0,
    name: "刺猬羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_14",
  },
  {
    abbreviation: "",
    clothesId: 22,
    id: 22,
    isTopic: 0,
    name: "鲨鱼羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_15",
  },
  {
    abbreviation: "",
    clothesId: 23,
    id: 23,
    isTopic: 0,
    name: "驯鹿羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_16",
  },
  {
    abbreviation: "",
    clothesId: 24,
    id: 24,
    isTopic: 0,
    name: "太空羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_17",
  },
  {
    abbreviation: "",
    clothesId: 25,
    id: 25,
    isTopic: 0,
    name: "粉粉羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_18",
  },
  {
    abbreviation: "",
    clothesId: 26,
    id: 26,
    isTopic: 0,
    name: "bug羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_19",
  },
  {
    abbreviation: "",
    clothesId: 27,
    id: 27,
    isTopic: 0,
    name: "茶壶羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_20",
  },
  {
    abbreviation: "",
    clothesId: 28,
    id: 28,
    isTopic: 0,
    name: "程序羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_21",
  },
  {
    abbreviation: "",
    clothesId: 29,
    id: 29,
    isTopic: 0,
    name: "小猪羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_22",
  },
  {
    abbreviation: "",
    clothesId: 30,
    id: 30,
    isTopic: 0,
    name: "吐司羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_23",
  },
  {
    abbreviation: "",
    clothesId: 31,
    id: 31,
    isTopic: 0,
    name: "蜗牛羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_24",
  },
  {
    abbreviation: "",
    clothesId: 32,
    id: 32,
    isTopic: 0,
    name: "蜜蜂羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_25",
  },
  {
    abbreviation: "",
    clothesId: 33,
    id: 33,
    isTopic: 0,
    name: "甜点羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_26",
  },
  {
    abbreviation: "",
    clothesId: 34,
    id: 34,
    isTopic: 0,
    name: "厨师羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_27",
  },
  {
    abbreviation: "",
    clothesId: 35,
    id: 35,
    isTopic: 0,
    name: "雪人羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_28",
  },
  {
    abbreviation: "",
    clothesId: 36,
    id: 36,
    isTopic: 0,
    name: "猴羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_29",
  },
  {
    abbreviation: "",
    clothesId: 37,
    id: 37,
    isTopic: 0,
    name: "花花羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_30",
  },
  {
    abbreviation: "",
    clothesId: 38,
    id: 38,
    isTopic: 0,
    name: "斯巴达羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_31",
  },
  {
    abbreviation: "",
    clothesId: 39,
    id: 39,
    isTopic: 0,
    name: "戴耳环的羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_32",
  },
  {
    abbreviation: "",
    clothesId: 40,
    id: 40,
    isTopic: 0,
    name: "圣诞羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_33",
  },
  {
    abbreviation: "五仁",
    clothesId: 41,
    id: 41,
    isTopic: 1,
    name: "五仁羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The04A",
  },
  {
    abbreviation: "豆沙",
    clothesId: 42,
    id: 42,
    isTopic: 1,
    name: "豆沙羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The04B",
  },
  {
    abbreviation: "咖啡",
    clothesId: 43,
    id: 43,
    isTopic: 1,
    name: "咖啡羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The05A",
  },
  {
    abbreviation: "茶",
    clothesId: 44,
    id: 44,
    isTopic: 1,
    name: "茶羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The05B",
  },
  {
    abbreviation: "嫦娥",
    clothesId: 45,
    id: 45,
    isTopic: 1,
    name: "嫦娥羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The06A",
  },
  {
    abbreviation: "玉兔",
    clothesId: 46,
    id: 46,
    isTopic: 1,
    name: "玉兔羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The06B",
  },
  {
    abbreviation: "夏",
    clothesId: 47,
    id: 47,
    isTopic: 1,
    name: "夏羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The07A",
  },
  {
    abbreviation: "冬",
    clothesId: 48,
    id: 48,
    isTopic: 1,
    name: "冬羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The07B",
  },
  {
    abbreviation: "奥比",
    clothesId: 49,
    id: 49,
    isTopic: 1,
    name: "奥比羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The08A",
  },
  {
    abbreviation: "摩尔",
    clothesId: 50,
    id: 50,
    isTopic: 1,
    name: "摩尔羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The08B",
  },
  {
    abbreviation: "",
    clothesId: 51,
    id: 51,
    isTopic: 0,
    name: "潮羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_34",
  },
  {
    abbreviation: "",
    clothesId: 52,
    id: 52,
    isTopic: 0,
    name: "咩咩羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_35",
  },
  {
    abbreviation: "",
    clothesId: 53,
    id: 53,
    isTopic: 0,
    name: "女仆羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_36",
  },
  {
    abbreviation: "",
    clothesId: 54,
    id: 54,
    isTopic: 0,
    name: "八戒",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_37",
  },
  {
    abbreviation: "",
    clothesId: 55,
    id: 55,
    isTopic: 0,
    name: "卧龙",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_38",
  },
  {
    abbreviation: "",
    clothesId: 56,
    id: 56,
    isTopic: 0,
    name: "星空羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_39",
  },
  {
    abbreviation: "",
    clothesId: 57,
    id: 57,
    isTopic: 0,
    name: "武圣",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_40",
  },
  {
    abbreviation: "",
    clothesId: 58,
    id: 58,
    isTopic: 0,
    name: "仓鼠羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_41",
  },
  {
    abbreviation: "",
    clothesId: 59,
    id: 59,
    isTopic: 0,
    name: "王子羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_42",
  },
  {
    abbreviation: "",
    clothesId: 60,
    id: 60,
    isTopic: 0,
    name: "渡渡羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_43",
  },
  {
    abbreviation: "",
    clothesId: 61,
    id: 61,
    isTopic: 0,
    name: "小虎羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_44",
  },
  {
    abbreviation: "",
    clothesId: 62,
    id: 62,
    isTopic: 0,
    name: "大象羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_45",
  },
  {
    abbreviation: "",
    clothesId: 63,
    id: 63,
    isTopic: 0,
    name: "牛牛羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_46",
  },
  {
    abbreviation: "",
    clothesId: 64,
    id: 64,
    isTopic: 0,
    name: "蚊子羊",
    platform: 1,
    spName: "Sheeps",
    spSkin: "skin_47",
  },
  {
    abbreviation: "足球",
    clothesId: 65,
    id: 65,
    isTopic: 1,
    name: "足球羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The09A",
  },
  {
    abbreviation: "篮球",
    clothesId: 66,
    id: 66,
    isTopic: 1,
    name: "篮球羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The09B",
  },
  {
    abbreviation: "沙滩",
    clothesId: 67,
    id: 67,
    isTopic: 1,
    name: "沙滩羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The10A",
  },
  {
    abbreviation: "雪山",
    clothesId: 68,
    id: 68,
    isTopic: 1,
    name: "雪山羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The10B",
  },
  {
    abbreviation: "护肤",
    clothesId: 69,
    id: 69,
    isTopic: 1,
    name: "护肤羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The11A",
  },
  {
    abbreviation: "美妆",
    clothesId: 70,
    id: 70,
    isTopic: 1,
    name: "美妆羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The11B",
  },
  {
    abbreviation: "复古",
    clothesId: 71,
    id: 71,
    isTopic: 1,
    name: "复古羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The13A",
  },
  {
    abbreviation: "流行",
    clothesId: 72,
    id: 72,
    isTopic: 1,
    name: "流行羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The13B",
  },
  {
    abbreviation: "户外",
    clothesId: 73,
    id: 73,
    isTopic: 1,
    name: "户外羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The14A",
  },
  {
    abbreviation: "宅",
    clothesId: 74,
    id: 74,
    isTopic: 1,
    name: "宅羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The14B",
  },
  {
    abbreviation: "科学",
    clothesId: 75,
    id: 75,
    isTopic: 1,
    name: "科技羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The15A",
  },
  {
    abbreviation: "艺术",
    clothesId: 76,
    id: 76,
    isTopic: 1,
    name: "艺术羊",
    platform: 1,
    spName: "ThemeSheeps",
    spSkin: "The15B",
  },
  {
    abbreviation: "",
    clothesId: 1000,
    id: 77,
    isTopic: 0,
    name: "羊了个羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1000",
  },
  {
    abbreviation: "",
    clothesId: 1001,
    id: 78,
    isTopic: 0,
    name: "卷羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1001",
  },
  {
    abbreviation: "",
    clothesId: 1002,
    id: 79,
    isTopic: 0,
    name: "节日羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1002",
  },
  {
    abbreviation: "",
    clothesId: 1003,
    id: 80,
    isTopic: 0,
    name: "披羊皮的狼",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1003",
  },
  {
    abbreviation: "",
    clothesId: 1004,
    id: 81,
    isTopic: 0,
    name: "汉堡羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1004",
  },
  {
    abbreviation: "",
    clothesId: 1005,
    id: 82,
    isTopic: 0,
    name: "水手羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1005",
  },
  {
    abbreviation: "",
    clothesId: 1006,
    id: 83,
    isTopic: 0,
    name: "乌龟羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1006",
  },
  {
    abbreviation: "夏",
    clothesId: 1007,
    id: 84,
    isTopic: 1,
    name: "夏羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1007A",
  },
  {
    abbreviation: "冬",
    clothesId: 1008,
    id: 85,
    isTopic: 1,
    name: "冬羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1007B",
  },
  {
    abbreviation: "狼人",
    clothesId: 1009,
    id: 86,
    isTopic: 1,
    name: "狼人羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1001A",
  },
  {
    abbreviation: "吸血鬼",
    clothesId: 1010,
    id: 87,
    isTopic: 1,
    name: "吸血鬼羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1001B",
  },
  {
    abbreviation: "",
    clothesId: 1013,
    id: 88,
    isTopic: 0,
    name: "寿司羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1007",
  },
  {
    abbreviation: "",
    clothesId: 1014,
    id: 89,
    isTopic: 0,
    name: "建设羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1008",
  },
  {
    abbreviation: "",
    clothesId: 1015,
    id: 90,
    isTopic: 0,
    name: "炸虾羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1009",
  },
  {
    abbreviation: "",
    clothesId: 1016,
    id: 91,
    isTopic: 0,
    name: "米饭羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1010",
  },
  {
    abbreviation: "",
    clothesId: 1017,
    id: 92,
    isTopic: 0,
    name: "恐龙羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1011",
  },
  {
    abbreviation: "",
    clothesId: 1018,
    id: 93,
    isTopic: 0,
    name: "煎蛋羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1012",
  },
  {
    abbreviation: "",
    clothesId: 1019,
    id: 94,
    isTopic: 0,
    name: "公主羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1013",
  },
  {
    abbreviation: "",
    clothesId: 1020,
    id: 95,
    isTopic: 0,
    name: "刺猬羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1014",
  },
  {
    abbreviation: "",
    clothesId: 1021,
    id: 96,
    isTopic: 0,
    name: "鲨鱼羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1015",
  },
  {
    abbreviation: "",
    clothesId: 1022,
    id: 97,
    isTopic: 0,
    name: "驯鹿羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1016",
  },
  {
    abbreviation: "",
    clothesId: 1023,
    id: 98,
    isTopic: 0,
    name: "太空羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1017",
  },
  {
    abbreviation: "",
    clothesId: 1024,
    id: 99,
    isTopic: 0,
    name: "粉粉羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1018",
  },
  {
    abbreviation: "",
    clothesId: 1025,
    id: 100,
    isTopic: 0,
    name: "Bug羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1019",
  },
  {
    abbreviation: "",
    clothesId: 1026,
    id: 101,
    isTopic: 0,
    name: "茶壶羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1020",
  },
  {
    abbreviation: "",
    clothesId: 1027,
    id: 102,
    isTopic: 0,
    name: "程序羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1021",
  },
  {
    abbreviation: "",
    clothesId: 1028,
    id: 103,
    isTopic: 0,
    name: "小猪羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1022",
  },
  {
    abbreviation: "",
    clothesId: 1029,
    id: 104,
    isTopic: 0,
    name: "吐司羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1023",
  },
  {
    abbreviation: "",
    clothesId: 1030,
    id: 105,
    isTopic: 0,
    name: "蜗牛羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1024",
  },
  {
    abbreviation: "",
    clothesId: 1031,
    id: 106,
    isTopic: 0,
    name: "蜜蜂羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1025",
  },
  {
    abbreviation: "",
    clothesId: 1032,
    id: 107,
    isTopic: 0,
    name: "甜点羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1026",
  },
  {
    abbreviation: "",
    clothesId: 1033,
    id: 108,
    isTopic: 0,
    name: "厨师羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1027",
  },
  {
    abbreviation: "",
    clothesId: 1034,
    id: 109,
    isTopic: 0,
    name: "雪人羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1028",
  },
  {
    abbreviation: "",
    clothesId: 1035,
    id: 110,
    isTopic: 0,
    name: "猴羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1029",
  },
  {
    abbreviation: "",
    clothesId: 1036,
    id: 111,
    isTopic: 0,
    name: "花花羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1030",
  },
  {
    abbreviation: "",
    clothesId: 1037,
    id: 112,
    isTopic: 0,
    name: "斯巴达羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1031",
  },
  {
    abbreviation: "",
    clothesId: 1038,
    id: 113,
    isTopic: 0,
    name: "戴耳环的羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1032",
  },
  {
    abbreviation: "",
    clothesId: 1039,
    id: 114,
    isTopic: 0,
    name: "圣诞羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1033",
  },
  {
    abbreviation: "",
    clothesId: 1040,
    id: 115,
    isTopic: 0,
    name: "潮羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1034",
  },
  {
    abbreviation: "",
    clothesId: 1041,
    id: 116,
    isTopic: 0,
    name: "咩咩羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1035",
  },
  {
    abbreviation: "",
    clothesId: 1042,
    id: 117,
    isTopic: 0,
    name: "仓鼠羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1041",
  },
  {
    abbreviation: "",
    clothesId: 1043,
    id: 118,
    isTopic: 0,
    name: "青蛙羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1042",
  },
  {
    abbreviation: "",
    clothesId: 1044,
    id: 119,
    isTopic: 0,
    name: "渡渡羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1043",
  },
  {
    abbreviation: "",
    clothesId: 1045,
    id: 120,
    isTopic: 0,
    name: "小虎羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1044",
  },
  {
    abbreviation: "",
    clothesId: 1046,
    id: 121,
    isTopic: 0,
    name: "大象羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1045",
  },
  {
    abbreviation: "",
    clothesId: 1047,
    id: 122,
    isTopic: 0,
    name: "牛牛羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1046",
  },
  {
    abbreviation: "",
    clothesId: 1048,
    id: 123,
    isTopic: 0,
    name: "蚊子羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1047",
  },
  {
    abbreviation: "足球",
    clothesId: 1049,
    id: 124,
    isTopic: 1,
    name: "足球羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1009A",
  },
  {
    abbreviation: "篮球",
    clothesId: 1050,
    id: 125,
    isTopic: 1,
    name: "篮球羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1009B",
  },
  {
    abbreviation: "沙滩",
    clothesId: 1051,
    id: 126,
    isTopic: 1,
    name: "沙滩羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1010A",
  },
  {
    abbreviation: "雪山",
    clothesId: 1052,
    id: 127,
    isTopic: 1,
    name: "雪山羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1010B",
  },
  {
    abbreviation: "护肤",
    clothesId: 1053,
    id: 128,
    isTopic: 1,
    name: "护肤羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1011A",
  },
  {
    abbreviation: "美妆",
    clothesId: 1054,
    id: 129,
    isTopic: 1,
    name: "美妆羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1011B",
  },
  {
    abbreviation: "",
    clothesId: 1055,
    id: 130,
    isTopic: 0,
    name: "女仆羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1036",
  },
  {
    abbreviation: "",
    clothesId: 1056,
    id: 131,
    isTopic: 0,
    name: "星空羊",
    platform: 2,
    spName: "Sheeps_Global",
    spSkin: "skin_1039",
  },
  {
    abbreviation: "复古",
    clothesId: 1057,
    id: 132,
    isTopic: 1,
    name: "复古羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1013A",
  },
  {
    abbreviation: "流行",
    clothesId: 1058,
    id: 133,
    isTopic: 1,
    name: "流行羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1013B",
  },
  {
    abbreviation: "户外",
    clothesId: 1059,
    id: 134,
    isTopic: 1,
    name: "户外羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1014A",
  },
  {
    abbreviation: "宅",
    clothesId: 1060,
    id: 135,
    isTopic: 1,
    name: "宅羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1014B",
  },
  {
    abbreviation: "科学",
    clothesId: 1061,
    id: 136,
    isTopic: 1,
    name: "科技羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1015A",
  },
  {
    abbreviation: "艺术",
    clothesId: 1062,
    id: 137,
    isTopic: 1,
    name: "艺术羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1015B",
  },
  {
    abbreviation: "猫猫",
    clothesId: 1063,
    id: 138,
    isTopic: 1,
    name: "猫猫羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1002A",
  },
  {
    abbreviation: "狗狗",
    clothesId: 1064,
    id: 139,
    isTopic: 1,
    name: "狗狗羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1002B",
  },
  {
    abbreviation: "咖啡",
    clothesId: 1065,
    id: 140,
    isTopic: 1,
    name: "咖啡羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1005A",
  },
  {
    abbreviation: "茶",
    clothesId: 1066,
    id: 141,
    isTopic: 1,
    name: "茶羊",
    platform: 2,
    spName: "ThemeSheeps_Global",
    spSkin: "The1005B",
  },
];

const getSkinName = (id) => {
  const skin = skins.find((sk) => sk.clothesId === id);
  if (skin) return skin.name;
  return id;
};

module.exports = { getSkinName };
